[profile.bench]
debug = true

[workspace]
resolver = "2"
members = [
    "memflow-registry",
    "memflow-registry-client",
    "memflow-registry-shared",
]
default-members = [
    "memflow-registry",
    "memflow-registry-client",
    "memflow-registry-shared",
]