name: Deploy to docker hub

on: [push, pull_request]
#on:
#  push:
#    tags:
#      - '*'
  
jobs:

  publish:
    runs-on: ubuntu-latest
    environment: publish
    steps:
      - uses: actions/checkout@v4
      - run: docker login -u ko1n -p ${{ secrets.DOCKER_HUB_TOKEN }}
      - run: docker build -t ko1n/memflow-registry:latest .
      - run: docker push ko1n/memflow-registry:latest
